ProjPPW/urls.py
from django.contrib import admin
from django.urls import path
from story6.views import * 
from django.views.generic.base import RedirectView
from django.conf.urls import include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.contrib.auth import views as auth_views

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


urlpatterns = [
	path('', RedirectView.as_view(url='main/')),
    path('admin/', admin.site.urls),
    path('main/', include(('story6.urls', 'story6'), namespace='story6')),
    path('booksapi/', get_books_api, name='getBooksApi'),
    path('searchBooks/', search_book, name='search-book'),
    #path('register/', register_account, name = 'register_new_account'),
    path('login/', my_view, name = 'login'),
    path('logout/', logout_view, name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),
    #path(API_ROOT + 'social/(?P<backend>[^/]+)/', exchange_token),
    path('api-auth/', include('rest_framework.urls')),
]

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'

story6/urls.py
from django.contrib import admin
from django.urls import path
from story6.views import * 
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', load_landing_page, name = 'landing_page_view'),
    path('save/', status_save, name = 'save_new_status'),

    ]

story6/models.py
from django.db import models
from django.utils import timezone

class UpdateStatus(models.Model):
	statusContent = models.TextField(max_length=256)
	dateTime = models.DateTimeField(default=timezone.now)

class AccountRegist(models.Model):
	username = models.CharField(max_length=64)
	#email = models.EmailField()
	password = models.CharField(max_length=64)


# Create your models here.

story6/forms.py
from django import forms

class StatusForm(forms.Form):
	statusContent = forms.CharField(label='',
		required=True,
		max_length=256,
		widget=forms.TextInput(attrs={'class' : 'input-group-text',
			'id' : 'status_field',
			'type':'text',
			'placeholder':'What\'s up?'})
		)

class RegistrationForm(forms.Form):
	username = forms.CharField(
		label='',
		required=True,
		max_length=64,
		widget=forms.TextInput(attrs={
			'class' : 'input-group-text',
			'name' : 'username',
			'id' : 'username1',
			'type' : 'text',
			'placeholder' : 'username',
			})
		)
	#email = forms.EmailField(
	#	label='',
	#	required=True,
	#	max_length=64,
	#	widget=forms.EmailInput(attrs={
	#		'class' : 'input-group-text',
	#		'name' : 'email_field',
	#		'id' : 'email_field1',
	#		'placeholder' : 'e-mail',
	#		})
	#	)
	password = forms.CharField(
		label='',
		required=True,
		max_length=64,
		min_length=8,
		widget=forms.PasswordInput(attrs={
			'class' : 'input-group-text',
			'name' : 'password_field',
			'id' : 'password_field1',
			'placeholder' : 'password',
			})
		)

story6/views.py
from django.contrib.auth import authenticate, login, logout
from rest_framework import serializers
from rest_framework import status
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

#from request.exceptions import HTTPError

from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


from .models import *
from .forms import *

import json, requests

response = {}
session = {}

def load_landing_page(request):
	response['new_status_field'] = StatusForm()
	response['status_all'] = UpdateStatus.objects.all()
	return render(request, 'header.html', response)

def status_save(request):
	form = UpdateStatus(request.POST or None)                       # UNTESTED
	if (request.method == 'POST'):
		response['statusContent'] = request.POST['statusContent']  
		new_status = UpdateStatus(
			statusContent=response['statusContent'])
		new_status.save()
		return HttpResponseRedirect('/main/')
	else : 
		form = UpdateStatus()
	return render(request, 'header.html')							# -----till here

def get_books_api(request):
	books = list()
	response = requests.get(url='https://www.googleapis.com/books/v1/volumes?q=quilting')
	data = response.json()
	for i in range (10) : 
		books.append({
			'id' : data['items'][i]['id'],
			'smallThumbnail' : data['items'][i]['volumeInfo']['imageLinks']['smallThumbnail'],
			'title' : data['items'][i]['volumeInfo']['title'],
			'authors' : data['items'][i]['volumeInfo']['authors'],
			'publishedDate' : data['items'][i]['volumeInfo']['publishedDate'],
			'previewLink' : data['items'][i]['volumeInfo']['previewLink'],
			})
	return JsonResponse({'books' : books})

def search_book(request, url):
	apiURL = 'https://www.googleapis.com/books/v1/volumes?q='
	if (request.method == 'POST') : # this will be GET now      
		book_name =  request.POST.get('search-box')
		print (book_name)
		apiURL += book_name.lower()    
	

# 	books = list()
# 	response = requests.get(url=apiURL)
# 	searchData = response.json()
# 	for i in range (10) : 
# 		books.append({
# 			'id' : searchData['items'][i]['id'],
# 			'smallThumbnail' : searchData['items'][i]['volumeInfo']['imageLinks']['smallThumbnail'],
# 			'title' : searchData['items'][i]['volumeInfo']['title'],
# 			'authors' : searchData['items'][i]['volumeInfo']['author'],
# 			'publishedDate' : searchData['items'][i]['volumeInfo']['publishedDate'],
# 			'previewLink' : searchData['items'][i]['volumeInfo']['previewLink'],
# 			})
# 	return JsonResponse({'books' : books})

# def register_account(request):
# 	response['registration_form'] = RegistrationForm()
# 	return render(request, 'headerRegist.html', response)

# def regist_validate_save(request):
# 	return render(request, 'header.html')

# def user_info_to_json(request):
# 	name = request.GET['name']
# 	email = request.GET['email']
# 	password = request.GET['password']
# 	return JsonResponse( {"name" : name,"email" : email, "password" : password}, safe=False )

def my_view(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		response['user'] = authenticate(request, username=username, password=password)
		if response['user'] is not None :
			response['user'].save()
			return HttpResponseRedirect('/main/')
		else : 
			return HttpResponse(status=403)
	else :	
		response['registration_form'] = RegistrationForm()
		return render(request, 'headerRegist.html', response)
	# Create a state token to prevent request forgery.
  

def logout_view(request):
	logout(request)
	for key in request.session.keys():
		del request.session[key]
	return HttpResponseRedirect('/login')


#referrence : https://github.com/coriolinus/oauth2-article/blob/master/views.py

story6/templates/footer.html
{% load static %}

{% block content %}

	<!-- jQuery, Popper.js, Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<!-- static Jquery, JS -->
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js' %}">
	</script> 
	{% csrf_token %}
	<script type="text/javascript" src="{% static 'js/customScript.js' %}">
	</script>
	


	</body>

</html>

{% endblock %}

story6/templates/header.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-signin-client_id" content="526386525514-f29l35be271olqnd942fsdardi6nlsh2.apps.googleusercontent.com"> <!--HARUS DIPINDAHIN-->

    <title>WeLc0M3</title>

    <!-- Bootstrap's CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom (static) CSS -->
    <link href="{% static '/css/style.css' %}" rel="stylesheet" id="custom-css-file">

    <!-- Custom fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,700,900" rel="stylesheet">
  </head>

  {% block content %}
  {% include "navbar.html" %}
  {% include "index.html" %}
  {% include "footer.html" %}
  {% endblock %}

</div>

story6/templates/headerRegist.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-signin-client_id" content="526386525514-f29l35be271olqnd942fsdardi6nlsh2.apps.googleusercontent.com"> <!--BUTUH DIPINDAHIN-->

    <title>WeLc0M3</title>

    <!-- Bootstrap's CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom (static) CSS -->
    <link href="{% static '/css/style.css' %}" rel="stylesheet" id="custom-css-file">

    <!-- Custom fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,700,900" rel="stylesheet">
  </head>

  {% block content %}
  {% include "regist.html" %}
  {% include "footer.html" %}
  {% endblock %}

</div>

story6/templates/index.html
	{% load staticfiles %}
	
	{% block content %}

	<!--- Page 1 --->



	<body id="page-top">
		<div class="page-1-1" id="page1">
			<div class="align-center">
				<div class="container">
					<div class="container-fluid">

						<!-- Greetings -->
						<br/><br/><br/><br/>
						<div class="row align-items-center">
							<div class="col align-self-start">
             					{% if user.is_authenticated %}  
                    				<p class="display-4">Hello {{ user.username }}, apa kabar?</p>
                				{% else %}
                  					<a class="lead">Login dulu cuy:)</a>
                				{% endif %}
							</div>
						</div>

						<!-- Field status update-->

						<div class="row">
							<div class="col-md-2 col-md-offset-5"> 
								<form id="form" method="POST" action="{% url 'story6:save_new_status' %}">

									{% csrf_token %}
									
									{{ new_status_field.as_p }}
									
									<input  type='submit' value='Post!' class="btn btn-primary btn-lg">
								</form>
							</div>
						</div>
					</div>	
				</div>
			</div>
			
		</div>
					
	

	    <!--- page 2 --->
		<div class="page-2-1" id="page2">
			<div class="align-center">
				<h1 class="text-big1-1">RECENT STATUS</h1>
				<br/><br/><br/>

				<!-- all status displayed here -->
				
					<div class="column-status">

						{% for data in status_all %}
						<div class="row">
							<div class="col">
								<div class="row align-items-center">
									<div class="col">
										<h4>
										{{ data.statusContent }}			
										</h4>
									</div>
								</div>
							</div>
							<div class="row align-items-end">
								<div class="col">
									<br/>	
									<p>
										{{ data.dateTime|date:"h:i A - d M Y"}}
									</p> 
								</div>
							</div>
						</div>
						<br/><br/>
						{% endfor %}	
					</div>
				</div>
			</div>
		</div>

	<!--- page 3 --->
		<div class="page-3-1" id="page3">
			<div class="container">
				<div class="align-centered">
					<br/><br/><br/>
					<div class="alert alert-primary"
						<p>
						Haloo.., perkenalkan nama saya Adam Maulana. Sekarang ini saya sedang berada dalam masa pendidikan tingkat 2 di Fasilkom Universitas Indonesia. Saya tinggal di kota Jakarta Utara. Untuk mengenal saya lebih lanjut, silahkan akses kotak <i>dropdown</i> di bawah ini. 
						</p> <br/><br/>	
					</div>
					<div class="alert alert-success">
						<div class="accordion">
							<dt><button type="button" class="btn btn-warning">Organisasi</button></dt>
							<dd>
								<li>FUKI Fasilkom -  2018--2019</li>
								<li>PASKIBRA SMAN 13 JAKARTA - 2014--2016</li>
								<li>SRI SMAN 13 Jakarta - 2014--2016</li>
								<br/>
							</dd><br/>
							<dt><button type="button" class="btn btn-secondary">Kepanitiaan</button></dt>
							<dd>
								<li>Seroja Muslim Festival 2015 - Dana & Usaha</li>
								<li>Studi Wisata Islam 2015 - Perlengkapan</li>
								<li>Studi Islam Instensif - PO</li>
								<li>Galas Flagtroops Event 9th--11th</li>
							</dd><br/>

							<dt><button type="button" class="btn btn-success">Aktivitas Terakhir</button></dt>
							<dd>
								<li>Rapat Dept - 08 Nov 2018</li>
								<li>Rapat BPH - 08 Nov 2018</li>
								<li>Service laptop - 07 Nov 2018</li> 
								<li>Rapat phynence - 07 Nov 2018</li>
								<li>Editing foto Kepanitiaan</li>
							</dd><br/>
							
							<dt><button type="button" class="btn btn-info">Prestasi</button></dt>
							<dd>
								<li>Juara 1 Kategori STEM - PestaSains IPB 2015</li>
								<li>Juara 3 LPBB - BAZKOM SMAN 68 Jakarta 2016</li>
								<li>Juara 1 Fotografi -  UI Store Merchandise Competition</li>
							</dd><br/>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="page-2-1" id = "page4">
			<br/><br/><br/>
			<div class="align-center">
				<h3 class="text-big1-1">Favorited Books! : <h3 id="favCount" class="text-big1-1">0</h3></h3>
				<br/><br/>
				<form method="GET" action="{% url 'search-book' %}">
					{% csrf_token %}
					<input class="form-control" type="text" placeholder="Search books..." name="search-box" id="search-box1">
					<button type="submit" class="btn btn-primary" id="searchBTN">Find!</button>
				</form>
				<div class="container-fluid">
					<div class="column-status">
						<button  type="button2" id="button2" name="button2" class="btn btn-info">
							Show books!
						</button>
						<br/>
							<div class="book-collections" id="book-collections">
								<table class="table" id="demo1">
									<thread>
										<tr>
											<th scope="col">#</th>
											<th scope="col">Cover</th>
											<th scope="col">Title</th>
											<th scope="col">Author</th>
											<th scope="col">Date Published</th>
											<th scope="col">Add to Favourite</th>
										</tr>
									</thread>
									<tbody id="volumes-table-body">
										
									</tbody>
								</table>
							</div>
					</div>
					<br/>
			</div>
		</div>




	</body>


	{% endblock %}

story6/templates/navbar.html
	{% load staticfiles %}

	{% block content %}

	<body id="page-top">

		<!-- Navigation Start Here -->
		<div class="pos-f-t">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4" id = "navbar_dark">
                <a class="text-navbar-1" href="/main/#page1">LANDING</a> <br/>
                <a class="text-navbar-1" href="/main/#page2">RECENT STATUS</a> <br/>
                <a class="text-navbar-1" href="/main/#page3">ABOUT</a> <br/>
                <a class="text-navbar-1" href="/main/#page4">BOOKS COLLECTION</a> <br/>
            </div>
        </div>
        	<nav class="navbar navbar-dark bg-dark">
            	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation" id="nav_button">
                <span class="navbar-toggler-icon"></span>
            	</button>

            	<button type="button" class="btn btn-secondary" onclick=changeTheme() id="th_switch">Change Theme</button>
                {% if user.is_authenticated %}  
                    <a class="text-navbar-1" href="/logout/">Log out</a>
                {% else %}
                    <a class="lead" href="{% url 'login' %}">Log in</a>
                {% endif %}
                

            </nav>
    	</div>

		<!-- Navigation End Here -->


		

	{% endblock %}

story6/templates/regist.html
	{% load staticfiles %}


	{% block content %}
	<body id="page-top">
		<div class="page-1-1" id="page1">
			<div class="align-center">
				<div class="container">
					<div class="container-fluid">

						<div class="row">
							<div class="col-md-2 col-md-offset-5"> 
								<form id="form_regist" method="POST" action="{% url 'login' %}">
									<br/><br/><br/><br/><br/><br/><br/>
		 							{% csrf_token %}

									{{ registration_form.as_p }}

									<input type='submit' value='login' class="btn btn-primary btn-lg"/>
								</form>
								<br/>

								<div class="g-signin2" data-onsuccess="onSignIn">
									{% csrf_token %}
									<button type="button" class="btn btn-light" id="gapi-signIn">Continue with Google</button>
								</div>
								<script src="https://apis.google.com/js/platform.js" async defer></script>
							</div>
						</div>
					</div>	
				</div>
			</div>
			
		</div>

	</body>
	{% endblock %}